config/routes.rb
Rails.application.routes.draw do
  devise_for :curators, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  root 'top#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :curator

  has_many :content_tags, dependent: destory
end

app/models/content_tag.rb
class ContentTag < ApplicationRecord
  belongs_to :content
  belongs_to :tag
end

app/models/curator.rb
class Curator < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable, :omniauthable, omniauth_providers: [:twitter]

  def self.find_for_oauth(auth)
    curator = Curator.find_by(uid: auth.uid, provider: auth.provider)

    curator ||= Curator.create(
      uid: auth.uid,
      provider: auth.provider,
      email: Curator.dummy_email(auth),
      password: Devise.friendly_token[0, 20]
    )

    curator
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :curator

  has_many :content_tags, dependent: destory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @curator = Curator.find_for_oauth(request.env['omniauth.auth'])

    if @curator.persisted?
      sign_in_and_redirect @curator, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_curator_registration_url
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    # TODO: メソッドを記述
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kyunration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <nav>
          <% if curator_signed_in? %>
            <%= link_to 'ログアウト', destroy_curator_session_path, method: :delete %>
          <% else %>
            <%= link_to 'サインアップ', new_curator_registration_path %>
            <%= link_to 'ログイン', new_curator_session_path %>
          <% end %>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>